-- MySQL Script generated by MySQL Workbench
-- Sun Nov 12 19:35:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Adventure_Works
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Adventure_Works
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Adventure_Works` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Adventure_Works` ;

-- -----------------------------------------------------
-- Table `Adventure_Works`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`CUSTOMERS` (
  `CustomerID` INT NOT NULL,
  `Firstname` VARCHAR(25) NULL DEFAULT NULL,
  `Lastname` VARCHAR(25) NULL DEFAULT NULL,
  `MaritalStatus` VARCHAR(25) NULL DEFAULT NULL,
  `Gender` VARCHAR(10) NULL DEFAULT NULL,
  `Email_Address` VARCHAR(25) NULL DEFAULT NULL,
  `AnnualIncome` DECIMAL(10,0) NULL DEFAULT NULL,
  `TotalChildren` SMALLINT NULL DEFAULT NULL,
  `EducationLevel` VARCHAR(25) NULL DEFAULT NULL,
  `Occupation` VARCHAR(25) NULL DEFAULT NULL,
  `HomeOwner` VARCHAR(25) NULL DEFAULT NULL,
  `BirthDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`Calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`Calendar` (
  `CalendarDate` DATE NOT NULL,
  `DayOfWeek` VARCHAR(20) NULL DEFAULT NULL,
  `DayOfMonth` INT NULL DEFAULT NULL,
  `DayOfYear` INT NULL DEFAULT NULL,
  `WeekOfMonth` INT NULL DEFAULT NULL,
  `Month` INT NULL DEFAULT NULL,
  `MonthName` VARCHAR(20) NULL DEFAULT NULL,
  `Quarter` INT NULL DEFAULT NULL,
  `Year` INT NULL DEFAULT NULL,
  `StartOfWeek` DATE NULL DEFAULT NULL,
  `StartOfMonth` DATE NULL DEFAULT NULL,
  `StartOfYear` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`CalendarDate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`PRODUCT_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`PRODUCT_CATEGORY` (
  `CategoryKey` SMALLINT NOT NULL,
  `CategoryName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CategoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`PRODUCT_SUBCATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`PRODUCT_SUBCATEGORY` (
  `SubCategoryKey` SMALLINT NOT NULL,
  `SubCategoryName` VARCHAR(100) NULL DEFAULT NULL,
  `CategoryKey` SMALLINT NOT NULL,
  PRIMARY KEY (`SubCategoryKey`),
  INDEX `CategoryKey` (`CategoryKey` ASC) VISIBLE,
  CONSTRAINT `product_subcategory_ibfk_1`
    FOREIGN KEY (`CategoryKey`)
    REFERENCES `Adventure_Works`.`PRODUCT_CATEGORY` (`CategoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`PRODUCT` (
  `ProductKey` SMALLINT NOT NULL,
  `SubCategoryKey` SMALLINT NOT NULL,
  `ProductSKU` VARCHAR(25) NULL DEFAULT NULL,
  `ProductName` VARCHAR(50) NULL DEFAULT NULL,
  `ModelName` VARCHAR(25) NULL DEFAULT NULL,
  `ProductDescription` VARCHAR(250) NULL DEFAULT NULL,
  `ProductColor` VARCHAR(25) NULL DEFAULT NULL,
  `ProductSize` INT NULL DEFAULT NULL,
  `ProductStyle` VARCHAR(25) NULL DEFAULT NULL,
  `ProductCost` DECIMAL(10,0) NULL DEFAULT NULL,
  `ProductPrice` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductKey`),
  INDEX `SubCategoryKey` (`SubCategoryKey` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`SubCategoryKey`)
    REFERENCES `Adventure_Works`.`PRODUCT_SUBCATEGORY` (`SubCategoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`TERRITORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`TERRITORY` (
  `TerritoryKey` SMALLINT NOT NULL,
  `REGION` VARCHAR(50) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(50) NULL DEFAULT NULL,
  `CONTINENT` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`TerritoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`RETURNS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`RETURNS` (
  `ReturnDate` DATE NULL DEFAULT NULL,
  `ProductKey` SMALLINT NOT NULL,
  `TerritoryKey` SMALLINT NOT NULL,
  `ReturnQuantity` INT NULL DEFAULT NULL,
  INDEX `ProductKey` (`ProductKey` ASC) VISIBLE,
  INDEX `TerritoryKey` (`TerritoryKey` ASC) VISIBLE,
  CONSTRAINT `returns_ibfk_1`
    FOREIGN KEY (`ProductKey`)
    REFERENCES `Adventure_Works`.`PRODUCT` (`ProductKey`),
  CONSTRAINT `returns_ibfk_2`
    FOREIGN KEY (`TerritoryKey`)
    REFERENCES `Adventure_Works`.`TERRITORY` (`TerritoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Adventure_Works`.`SALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adventure_Works`.`SALES` (
  `OrderDate` DATE NULL DEFAULT NULL,
  `StockDate` DATE NULL DEFAULT NULL,
  `OrderNumber` SMALLINT NOT NULL,
  `ProductKey` SMALLINT NOT NULL,
  `CustomerID` INT NOT NULL,
  `TerritoryKey` SMALLINT NOT NULL,
  `OrderItem` INT NULL DEFAULT NULL,
  `OrderQuantity` INT NULL DEFAULT NULL,
  INDEX `ProductKey` (`ProductKey` ASC) VISIBLE,
  INDEX `CustomerID` (`CustomerID` ASC) VISIBLE,
  INDEX `TerritoryKey` (`TerritoryKey` ASC) VISIBLE,
  CONSTRAINT `sales_ibfk_1`
    FOREIGN KEY (`ProductKey`)
    REFERENCES `Adventure_Works`.`PRODUCT` (`ProductKey`),
  CONSTRAINT `sales_ibfk_2`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `Adventure_Works`.`CUSTOMERS` (`CustomerID`),
  CONSTRAINT `sales_ibfk_3`
    FOREIGN KEY (`TerritoryKey`)
    REFERENCES `Adventure_Works`.`TERRITORY` (`TerritoryKey`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
